name: "My Health Check"
url: "https://github.com/kwatkins/homeassistant_addons/tree/main/myhealth_check"
description: "A simple health check for your home assistant instance"
version: "8.0"
slug: myhealth_check
init: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  9091/tcp: 9091
options:
  port: 9091
schema: 
  port: int
